### ISSUE TITLE
can not play rtmp stream without audio

### ISSUE THREAD

**Issue by erlangp** [ant-media/ExoPlayer-with-RTMP-and-FLV-seek#2]
### Issue description
Can not play RTMP stream without audio

### Reproduction steps
Change url to an RTMP URL that does not contains audio (video only)

### Version of ExoPlayer being used
ExoPlayer-with-RTMP-and-FLV-seek-master

### Device(s) and version(s) of Android being used
Oppo R831 (API 17)

**Comment by mekya** [comment]
Hi @erlangp,
Is it possible to give me rtmp url that I can try?

Regards,
A. Oguz

**Comment by erlangp** [comment]
thanks before :D
this link:
rtmp://  182.23.113.141  :1935  /  live  /  tirtanadi.stream
i have try play that stream url using vlc media player ( on windows ) and work

**Comment by erlangp** [comment]
how to play that link using ExoPlayer-with-RTMP-and-FLV-seek ?
i have try but get `idle` state

**Comment by mekya** [comment]
Thank you for the url.

I am gonna try to debug it today and let you know the status.

Sorry for late reply.

**Comment by mekya** [comment]
Hi @erlangp ,
The problem is fixed. It is not about not having audio. It is about original FLVExtractor throws exception if script data tag is not ecma array. I [comment out that line. ](https://github.com/ant-media/ExoPlayer-with-RTMP-and-FLV-seek/commit/a55c217f46ff88d6ce795885eb5bc161eece2995)

It is playing right now.

**Comment by erlangp** [comment]
thanks !!! :smile: :+1:
